# For more info on HTTP files go to https://aka.ms/vs/httpfile

GET https://uat-api.3ona.co/exchange/v1/public/get-instruments

###
GET https://uat-api.3ona.co/exchange/v1/public/get-tickers

###
GET https://uat-api.3ona.co/exchange/v1/public/get-valuations

###
GET https://uat-api.3ona.co/exchange/v1/public/get-candlestick

###
GET https://uat-api.3ona.co/exchange/v1/public/get-valuations?instrument_name=ENSUSD-INDEX&valuation_type=index_price&count=50


###
GET https://uat-api.3ona.co/exchange/v1/public/get-valuations?instrument_name=ENS_USD

###
GET https://uat-api.3ona.co/v2/public/get-ticker?instrument_name=ENS_USD

###
GET https://uat-api.3ona.co/public/get-trades?instrument_name=ENS_USD&count=5

